# .JuliaFormatter.toml


margin = 92
indent = 4
style = "default"
remove_extra_newlines = true
always_use_return = false
format_docstrings = true
join_lines_based_on_source = true
separate_kwargs_with_semicolon = true
format_markdown = true
trailing_comma = false
long_to_short_function_def = true